[package]
name = "RichPresence"
version = "0.1.0"
edition = "2024"

[dependencies]
BSDataPuller = { path = "../BSDataPuller" }
discordipc = "0.1.1"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }
